Zorbus\SymfonyBootstrapBundle\Entity\Bundle:
    type: entity
    table: zorbus_symfony_bootstrap_bundle
    repositoryClass: Zorbus\SymfonyBootstrapBundle\Entity\BundleRepository
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        name:
            type: string
            length: 255
            nullable: false
        class:
            type: string
            length: 255
            nullable: false
        website:
            type: string
            length: 255
            nullable: true
        category:
            type: string
            length: 255
        is_enabled:
            type: boolean
            default: true
            nullable: true